= ownCloud Web
:toc: right

:description: ownCloud web comes with a completely new design that is more user-friendly and intuitive and, of course, optimized for Infinite Scale.

== Introduction

{description}

If you are still running ownCloud 10.x as server, consider installing the {oc-marketplace-url}/apps/web[Web] app, which provides the new look and feel plus some additional features, but not everything ownCloud Web has to offer when used with Infinite Scale. For a quick introduction about what's new or different, check out the section xref:web_with_oC10.adoc[ownCloud Web on ownCloud Server 10.x].

== Changes

For readers already familiar with ownCloud 10 and its standard web interface, the big differences in the new ownCloud Web on Infinite Scale are:

* Spaces: Spaces are special folders for teams. They are ogranized by the team members itself so that admins don't need to manage them. Even if members leave, the files stay in place so your team can keep on working.
* Simplified links: Just select if only invited people or everyone can access a link. In consequence, we no longer distinguish between private and public links.
* Simplified sharing, for example: Get links with only 1 click or see at a glance who and which links are giving access.

// There's probably more worth mentioning...
// Search is done via Bleve https://github.com/blevesearch/bleve

// As an admin, check out the section [ownCloud Web for Admins]. Users can find out more about how the new web interface works in the section [ownCloud Web for Users].

== Security Aspects

The development of ownCloud Web is closely aligned to the development of Infinite Scale. Read the Infinite Scale xref:{latest-ocis-version}@ocis:ROOT:security/security.adoc[Security Aspects] document for details.
