= ownCloud Web
:toc: right
:description: ownCloud web comes with a completely new design that is more user-friendly and intuitive and, of course, optimized for Infinite Scale.

== Introduction

{description}

If you are still running ownCloud Server, consider installing the {oc-marketplace-url}/apps/web[Web] app, which provides the new look and feel plus some additional features, but not everything ownCloud Web has to offer when used with Infinite Scale. For a quick introduction about what's new or different, check out the section xref:web_with_oc_server.adoc[ownCloud Web on ownCloud Server].

== Changes

For readers already familiar with ownCloud 10 and its standard web interface, the big differences in the new ownCloud Web on Infinite Scale are:

* Spaces: Spaces are special folders for teams. They are organized by the team members themselves so that admins don't need to manage them. Even if members leave, the files stay in place so your team can keep on working.
* Simplified links: Just select if only invited people or everyone can access a link. In consequence, we no longer distinguish between private and public links.
* Simplified sharing, for example: Get links with only 1 click or see at a glance who and which links are giving access.

== Security Aspects

The development of ownCloud Web is closely aligned to the development of Infinite Scale. Read the Infinite Scale https://doc.owncloud.com/ocis/next/deployment/security/security.html[Security Aspects] document for more details.
