=== Configuring ownCloud Web

There are a few configuration settings necessary for ownCloud Web to work correctly. Copy the example config below into the `config/config.json` file (create one if it does not exist) and adjust it for your environment:

[source,plaintext]
----
{
  "server" : "https://<your-owncloud-server>",
  "theme": "https://<your-owncloud-server>/themes/owncloud/theme.json",
  "auth": {
    "clientId": "<client-id-from-oauth2>",
    "url": "https://<your-owncloud-server>/index.php/apps/oauth2/api/v1/token",
    "authUrl": "https://<your-owncloud-server>/index.php/apps/oauth2/authorize"
  },
  "apps" : [
    "files",
    "preview",
    "draw-io"
  ],
  "applications" : [
    {
      "title": {
        "en": "Classic Design",
        "de": "Klassisches Design",
        "fr": "Design classique",
        "zh_CN": "文件"
      },
      "icon": "swap-box",
      "url": "https://<your-owncloud-server>/index.php/apps/files"
    },
    {
      "icon": "settings-4",
      "menu": "user",
      "target": "_self",
      "title": {
        "de": "Einstellungen",
        "en": "Settings"
      },
      "url": "https://<your-owncloud-server>/index.php/settings/personal"
    }
  ]
}
----

If you use OpenID Connect instead of OAuth2, you need to replace the "auth" part with the following configuration:

[source,plaintext]
----
  "openIdConnect": {
    "metadata_url": "<fqdn-of-the-identity-provider>/.well-known/openid-configuration",
    "authority": "<fqdn-of-the-identity-provider>",
    "client_id": "<client-id-from-the-identity-provider>",
    "response_type": "code",
    "scope": "openid profile email"
  }
----

TIP: If any issues arise when trying to access the new design, a good start for debugging is to let a json validator check your `config.json` file.

[caption=]
[cols="30%,70%",options="header",]
|===
| Parameter
| Description

| server
| ownCloud 10 server address

| theme
| theme to be used in ownCloud Web pointing to a json file in the themes folder

| auth.clientId
| Client ID received when ownCloud Web was added in the `User Authentication` section by the admin

| apps
| List of internal extensions to load

| applications
| Additional apps and links to be displayed in the application switcher or in the user menu

| applications[0].title
| Title visible in the application switcher or user menu, localizable

| applications[1].menu
| Use `user` if the menu item should be displayed in the user menu (defaults to app switcher).
|===

NOTE: Do not place the `config.json` file in the app folder. If you do, the integrity check of the app will fail and issue warnings.
